# Generated by Django 5.1 on 2024-08-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_employee_groudid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='groudId',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_groudId',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
