# Generated by Django 5.1 on 2024-08-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_employee_groudid_employee_employee_groudid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_groudId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
