# Generated by Django 5.1 on 2024-08-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_employee_employee_groudid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_groudId',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
