# Generated by Django 5.1 on 2024-08-11 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_employee_employee_groudid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='compagny',
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.CharField(default='IT', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_groudId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.employeegroup'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
