# Generated by Django 5.1 on 2024-08-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_employee_compagny_employee_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
